version: '3'

services:
  database:
    container_name: crepe-mysql
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: crepedb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/crepedb
    networks:
      - app-tier
    tty: true

  backend:
    container_name: crepe-backend
    build:
      context: ./
    command: gradle bootRun
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - database
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null